### ISSUE TITLE
Add support for env vars instead of CLI arguments?

### ISSUE THREAD

**Issue by pkoch** [mattbrictson/minitest-snapshots#4]
It's a matter of style, but it shouldn't be too hard to implement, doesn't bloat the code too much and some people (like me) would much rather have that (instead of running the risk of clashing with other extensions defining their own args).

Would you be open to a PR on this?

**Comment by airhorns** [comment]
Sorry about the long delay -- yep would be totally fine with a PR! Makes sense for integrating with other test runners on top of minitest for sure.

**Comment by pkoch** [comment]
What do you think these should be named? The only source for inspiration I found was https://github.com/bahmutov/snap-shot-it#advanced-use, but I didn't feel very convinced. I thought that jest had some mechanism like this where we could draw inspiration from, but I was wrong.

Do you have any examples you wanna follow? Maybe some names in mind already? If not, I'd say let's just roll with `UPDATE_SNAPSHOTS` and `LOCK_SNAPSHOTS`.

**Comment by mattbrictson** [comment]
Hi @pkoch , not sure if you are still interested, but I would be open to a PR for this. My recommendation would be `MT_UPDATE_SNAPSHOTS` and `MT_LOCK_SNAPSHOTS`, since there is a precedent for using the `MT_` prefix for Minitest.

https://github.com/minitest/minitest/blob/a2c6c18570f6f0a1bf6af70fe3b6d9599a13fdd6/lib/minitest.rb#L141

**Comment by pkoch** [comment]
Uff, it's been a while. I'm not using this anymore. 😅

Let's close this for now. I'll open up a new issue if I ever get back into a contributing position.
