### ISSUE TITLE
Expected snapshot in CI does not correspond to snapshot generated locally from v1.1.0

### ISSUE THREAD

**Issue by mikevoets** [mattbrictson/minitest-snapshots#51]
Hi!

We're having some issues with upgrading to v1.1.0.

The snapshot that we create locally does not seem to correspond to the snapshot that it's expecting when it's running the tests in CI.

This seems to be caused by the fact that locally, from 1.1.0, it adds:

```
...
```

to the end of the snapshot, whereas before it would add a newline.

Do you have any advice on what to do here? Is there something we need to fix on our end?

**Comment by mattbrictson** [comment]
Thanks for the report. Sorry to hear you are running to this problem.

What version of minitest-snapshots were you running prior to upgrading to 1.1.0? The reason I ask is because the snapshot format was changed from plain strings to YAML at some point in the history of the gem. If you were previously using a version older than 1.0.0, you may need to re-record your snapshots.

If you are upgrading from 1.0.0 (i.e. your snapshots are already YAML-formatted), then this gets tricky. I have not seen the `...` YAML document terminator before, but it is apparently a thing: https://stackoverflow.com/questions/66542271/what-does-three-dots-in-a-yaml-yml-mean

So perhaps local and CI have Ruby compiled against different versions of libyaml?

Can you try the following in both environments?

```ruby
require "yaml"
Psych::VERSION
# => "5.1.2"
Psych::LIBYAML_VERSION
# => "0.2.5"
```

Otherwise, is there something happening in the CI environment that is patching the behavior of `.to_yaml` (this is what minitest-snaphots is using to serialize to YAML)? Maybe some library is being eagerly loaded in CI that affects it?

**Comment by mikevoets** [comment]
Hi @mattbrictson, thanks for your prompt reply!

Here's what we have locally:

```
irb(main):004> Psych::VERSION
=> "3.3.4"
irb(main):005> Psych::LIBYAML_VERSION
=> "0.2.5"
```

And here's what we have in CI:

```
irb(main):001> Psych::VERSION
=> "3.3.4"
irb(main):002> Psych::LIBYAML_VERSION
=> "0.2.2"
```

So you're right! Wonder what the resolution to this would be? libyaml is installed as binary, isn't that correct?

**Comment by mattbrictson** [comment]
@mikevoets honestly it has been a while since I've run into LibYAML issues, so I am not sure what the best resolution would be.

I would start by trying to upgrade the actual LibYAML library, which should be provided as a system package. For example:

```
sudo apt-get update
sudo apt-get install libyaml-dev
```

You may also need to recompile Ruby after updating LibYAML.

**Comment by mikevoets** [comment]
Hey @mattbrictson, thanks a lot.

Our CI nodes are running on Ubuntu, which don't have access to libyaml 0.2.5 via apt, but we have the following workaround in CI in place which solves this issue:

```
wget http://mirrors.kernel.org/ubuntu/pool/main/liby/libyaml/libyaml-0-2_0.2.5-1_amd64.deb
sudo apt-get install -y ./libyaml-0-2_0.2.5-1_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/main/liby/libyaml/libyaml-dev_0.2.5-1_amd64.deb
sudo apt-get install -y ./libyaml-dev_0.2.5-1_amd64.deb
apt-cache policy libyaml-dev
```

Thanks a lot for the help with troubleshooting! Hope you have a good day wherever you are.

**Comment by mattbrictson** [comment]
Glad to hear it's working! Cheers~
